// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOZxAytfOwsiUwPaMaPDg8T65U60iTag',
    appId: '1:567562983329:web:53aadd3508a76617b11de0',
    messagingSenderId: '567562983329',
    projectId: 'hackathon-e99a8',
    authDomain: 'hackathon-e99a8.firebaseapp.com',
    storageBucket: 'hackathon-e99a8.appspot.com',
    measurementId: 'G-GVSGC7YRQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG7nub4qK0F2tWJslYhzrPUvalDLtZ80M',
    appId: '1:567562983329:android:b9e4cd9374070948b11de0',
    messagingSenderId: '567562983329',
    projectId: 'hackathon-e99a8',
    storageBucket: 'hackathon-e99a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYByezceXIJA-Pfruu2z5klXaQdWZ2TGY',
    appId: '1:567562983329:ios:e6077526807e07eeb11de0',
    messagingSenderId: '567562983329',
    projectId: 'hackathon-e99a8',
    storageBucket: 'hackathon-e99a8.appspot.com',
    iosClientId: '567562983329-tmh779f1oafpd3arh89gm0hfnrtanf35.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackatonProject',
  );
}
